# Generated by Django 4.1.5 on 2023-01-23 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0003_category_remove_product_id_alter_product_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')])),
                ('description', models.CharField(max_length=200)),
                ('product_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_food.product')),
            ],
        ),
    ]
